### ISSUE TITLE
Make File-References in output clickable

### ISSUE THREAD

**Issue by pbihler** [TabDigital/atom-mocha-test-runner#13]
It would be of great help if the file-references in the output (from stacktraces) would be clickable just like URLs, and open the file at the defined postion where the error occured...

**Comment by pbihler** [comment]
done in PR #16

**Comment by achingbrain** [comment]
Is there any extra config you need to do to make this work?  Whenever I click a file path in the stack trace from the test output (e.g. `project/foo/bar.js`), I get a pop-up from atom saying 'File not found: project/foo/bar.js'.

**Comment by rprieto** [comment]
Can you tell us more about your project setup?
- Are you opening `atom` at the root of the project, or one level above?
- Does your project have a `package.json` at the root?
- Is this particular path (`project/foo/bar.js`) relative to `package.json`?
