### ISSUE TITLE
Add option to display test status in sidebar

### ISSUE THREAD

**Issue by fixe** [TabDigital/atom-mocha-test-runner#22]
What about adding a test status to the sidebar just like `Wallaby`? More info in the [DailyJS article](http://dailyjs.com/2015/02/17/wallaby-bbc/).

**Comment by rprieto** [comment]
`Wallaby` looks very cool, thanks! I'm not sure about implementing the same thing though... should we leave that to Wallaby, if/when they add `Atom` support (they already have 5+ IDEs)?

Needs more thinking, but I would assume you could install both plugins, `Wallaby` for the sidebar test reports & coverage, and `mocha-test-runner` to run selected tests and get test output right there in Atom.

**Comment by fixe** [comment]
Sure why not. I'll send a request :-)
