### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by JsonHunt** [TabDigital/atom-mocha-test-runner#23]
Failed to run Mocha
spawn C:\git\callfanout\node_modules\.bin\mocha ENOENT

**Comment by rprieto** [comment]
Thanks for reporting this. It should be related to these lines:

```coffee
# context.coffee

exports.find = (editor) ->
  root = closestPackage editor.getPath()
  if root
    mochaBinary = path.join root, 'node_modules', '.bin', 'mocha'
```

Nothing weird jumps out for now, but we'll investigate.
Do you mind running with the `Show context information` flag turned on in the settings, and pasting the output here?

**Comment by Codesleuth** [comment]
Same problem here, Atom 0.186.0 with mocha-test-runner 0.4.0.

```
Node binary:    /usr/local/bin/node
Root folder:    C:\dev\project
Path to mocha:  C:\dev\project\node_modules\.bin\mocha
Debug-Mode:     false
Test file:      test\handler.tests.js
Selected test:  null

Failed to run Mocha
spawn C:\dev\project\node_modules\.bin\mocha ENOENT
```

It appears to be executing the shell version of the file, not `mocha.cmd` as expected. If I change context.coffee to force the `.cmd` extension, I get this:

```
Node binary:    /usr/local/bin/node
Root folder:    C:\dev\project
Path to mocha:  C:\dev\project\node_modules\.bin\mocha.cmd
Debug-Mode:     false
Test file:      test\handler.tests.js
Selected test:  null

'node' is not recognized as an internal or external command,
operable program or batch file.
```

Which leads me to believe it doesn't have `PATH` available. Since mocha is run from the context of the project folder, placing the following file named `node.cmd` in your project root as well as the `context.coffee` change above will work around this problem:

```cmd
@echo off
"C:\Program Files\nodejs\node.exe" %*
```

_(Change the node.exe location if different)_

Let me know if you need any more information.

**Comment by Codesleuth** [comment]
Right after writing that comment I found the node binary path option. When I set that to the quoted path (`"C:\Program Files\nodejs\node.exe"`) using the modified `mochaBinary` value, I then get the following exception from `event.js`:
```
'ps' could not be spawned. is it installed and on your path? if so please open an issue on the package spawning the process.
```

It looks like `process.kill` in [mocha.coffee#L102](https://github.com/TabDigital/atom-mocha-test-runner/blob/2bdbb88e1757aa40c4c520f96f917a387df400db/lib/mocha.coffee#L102) is attempting to run `ps` and fails on Windows. [`tree-kill`](https://www.npmjs.com/package/tree-kill) may be more suitable? Incoming pull request for these two issues.

**Comment by ginus** [comment]
'ps' could not be spawned. +1

**Comment by gitseitanaka** [comment]
@rprieto Hello! :smile: 
Is this issue close by #24 ?
Just in case, pasting the output, when running with the "Show context" information flag turned on in the settings.

[Enter steps to reproduce below:]

1. 'ctl + alt + m'
2. 'Failed to run Mocha'

**Atom Version**: 0.211.0
**System**: Windows7(64bit)
**Thrown From**: [mocha-test-runner](https://github.com/TabDigital/atom-mocha-test-runner) package, v0.4.2


### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\Users\user\.atom\packages\mocha-test-runner\lib\context.coffee:7

TypeError: undefined is not a function
  at Object.exports.find (C:\Users\user\.atom\packages\mocha-test-runner\lib\context.coffee:7:32)
  at Object.module.exports.run (C:\Users\user\.atom\packages\mocha-test-runner\lib\mocha-test-runner.coffee:70:30)
  at atom-workspace.module.exports.activate.subscriptions.add.atom.commands.add.mocha-test-runner:run (C:\Users\user\.atom\packages\mocha-test-runner\lib\mocha-test-runner.coffee:50:89)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\user\AppData\Local\atom\app-0.211.0\resources\app.asar\src\command-registry.js:241:29)
  at __bind (C:\Users\user\AppData\Local\atom\app-0.211.0\resources\app.asar\src\command-registry.js:3:61)
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\user\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\user\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\user\AppData\Local\atom\app-0.211.0\resources\app.asar\src\window-event-handler.js:180:20)

```

### Commands

```
     -0:18.1.0 core:cut (atom-text-editor#mocha-test-runner.options.editor.mini.is-focused)
     -0:08.7.0 mocha-test-runner:run (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "mocha-test-runner": {
    "showContextInformation": true,
    "nodeBinaryPath": "C:/Program Files/nodejs/node"
  }
}
```

### Installed Packages

```coffee
# User
mocha-test-runner, v0.4.2

# Dev
No dev packages
```

**Comment by jonira** [comment]
+1 I'm having the same issue

**Comment by kristok** [comment]
+1 config seems same as in one of the examples above so no point in adding it.

**Comment by vingorius** [comment]
+1 I'm having the same issue

**Comment by rprieto** [comment]
Just merged a fix for this, huge thanks to @Codesleuth and sorry for the late merge! New version is available as `0.4.5`.

**Comment by cnaccio** [comment]
Even after the 0.4.5 update I was still having the 'ps' could not be spawned issue. I was able to resolve the issue by substituting out ps-tree for process-tree which works in Windows. Everything is working as expected.

**Comment by zanon-io** [comment]
@cnaccio, I've found that you don't need to change the module **ps-tree** to **process-tree** if the mocha-test-runner manages to find the Node executable correctly (without the [node.cmd trick](https://github.com/TabDigital/atom-mocha-test-runner/issues/23#issuecomment-77752795)). 

I've fixed it with PR [#50](https://github.com/TabDigital/atom-mocha-test-runner/pull/50) and the error `'ps' could not be spawned.` is not happening anymore. 

Thx anyway. You suggestion, combined with the node.cmd trick, helped me before I had the time to dig into the code.

**Comment by zanon-io** [comment]
My PR #50 fixes the Node binary not found and avoid the need of [adding a node.cmd](https://github.com/TabDigital/atom-mocha-test-runner/issues/23#issuecomment-77752795) for each project root.

However, as @cnaccio has mentioned, it is still necessary to change the module **ps-tree** to **process-tree** for Windows users (at lib\mocha.coffe line 7) to avoid the warning `'ps' could not be spawned`.

As I would need to test it in Linux/OSX, I didn't create a PR for that. If someone else have the time to test it, it would be nice.

**Comment by rprieto** [comment]
Thanks @zanon-io, I just merged your fix. Until it's released, you *should* be able to update the `Node binary path` setting in the Atom preference pane.

Good catch @cnaccio, I'll have a look at the `process-tree` issue and check it still works on OSX.

**Comment by batjko** [comment]
This seems like it should be an easy fix, i.e. testing which platform we're on and requiring either ps-tree or process-tree accordingly, no?

I'll see if I can try it out and open a PR sometime...
