### ISSUE TITLE
Question: Setting Options

### ISSUE THREAD

**Issue by robhicks** [TabDigital/atom-mocha-test-runner#25]
Please provide greater details on setting options. The Settings pane doesn't include any options for your package. I need to add transpilation.

**Comment by rprieto** [comment]
Hi, that's odd. The settings pane should contain all options mentioned in the README. Do you mind posting a screenshot?

**Comment by rprieto** [comment]
*Note:* if you're transpiling from CoffeeScript for example, it's good practice to add that in `test/mocha.opts`, which is automatically picked-up by Mocha.

```bash
--compilers coffee:coffee-script/register
```

**Comment by robhicks** [comment]
@rprieto I reinstalled it and was able to see the settings. 

Thanks for the tip on mocha.opts. That works well.

**Comment by rprieto** [comment]
No worries, happy it's fixed!
