### ISSUE TITLE
Values to be set on "Settings" not shown

### ISSUE THREAD

**Issue by marcopiraccini** [TabDigital/atom-mocha-test-runner#26]
The Readme says: "If you go to the settings pane, you can set the following values"...but it's not true :)
I'm using Atom 0.190.0 on Ubuntu 64.

**Comment by rprieto** [comment]
Hi, can you have a look #25 & see if it's the same issue?

**Comment by marcopiraccini** [comment]
Yes, it seems to be the same issue. The guy resolved it reinstalling, but it didn't work for me

**Comment by rprieto** [comment]
Sorry about that. So is your settings page completely blank?
What's the version of both `Atom` and `mocha-test-runner`?

**Comment by marcopiraccini** [comment]
In "Settings" I see only the "Keybindings" and the "README" sections (so it's not completely blank).
These are the versions: 
Atom: 0.190.0
mocha-test-runner: 0.4.0

**Comment by marcopiraccini** [comment]
Update: I've installed the last atom release (0.192) and now I can see the settings! 
I'm gonna close this issue.

**Comment by rprieto** [comment]
Good to hear, thanks.
We couldn't reproduce here so I can only think it was an Atom version issue.
