### ISSUE TITLE
Expose the console CSS classes

### ISSUE THREAD

**Issue by marcopiraccini** [TabDigital/atom-mocha-test-runner#32]
I need to change the appearance of the test execution results (too small): font family, size, etc. 
Shall we expose as configuration these styles?
Or at least document which classes should be changed (globally) to change the test result appearance

**Comment by rprieto** [comment]
Good question, what's a good practice for atom plugins? It might be weird exposing full CSS as options, but maybe `font-size` as an integer for example? (family is monospace)

**Comment by marcopiraccini** [comment]
In atom, the full CSS it's already customizable, if we know the used classes.

**Comment by rprieto** [comment]
Thanks, I'll add the main CSS classes to the README.

**Comment by rprieto** [comment]
Done :)
