### ISSUE TITLE
Text color is missing

### ISSUE THREAD

**Issue by kengz** [TabDigital/atom-mocha-test-runner#36]
I left the "text-only" option blank so it should show colors, but here's what I got, all-white font:

![screen shot 2015-06-13 at 8 08 40 pm](https://cloud.githubusercontent.com/assets/8209263/8146482/121f6004-1208-11e5-98a6-1be7bb488b32.png)

**Comment by rprieto** [comment]
Thanks for the report, that's odd. What's your version of `Atom` and `mocha-test-runner`?

**Comment by kengz** [comment]
0.209.0 and 0.4.2 respectively.

**Comment by mattgoucher** [comment]
Confirmed same issue on *Atom 1.0.0* and *mocha-test-runner 0.4.2*

**Comment by ramification** [comment]
The solution for me was to force colors with the "-C" option

**Comment by rprieto** [comment]
Thanks good to know. Just to clarify do you mean `-c`?

>  -c, --colors                  : force enabling of colors
>  -C, --no-colors            : force disabling of colors

Maybe it's safer for `mocha-test-runner` to always append `-c` then... @nguyenchr what do you think?

**Comment by ramification** [comment]
sorry, it's the -c (lowerCase) ! ^_^"

**Comment by nguyenchr** [comment]
@rprieto sounds like a good idea
we would have to strip the ansi colour codes from the output if the textonly option is selected

**Comment by rprieto** [comment]
Or depending on whether they select `text only`, we call mocha with `-c` or `-C`?

**Comment by nguyenchr** [comment]
I just published `0.4.4` which should fix this problem, let me know if there are any issues

**Comment by mattgoucher** [comment]
Looks great! Thanks @nguyenchr
