### ISSUE TITLE
Add a summary to the title bar

### ISSUE THREAD

**Issue by rprieto** [TabDigital/atom-mocha-test-runner#4]
For example:

- When running: `Mocha test results: ...`
- When finished: `Mocha test results: 3 / 4 passed`

This makes it easier to see the global status at a glance, even if the window is too small for dozens of tests.

**Comment by pbihler** [comment]
Implemented in PR #17

**Comment by rprieto** [comment]
#17 was merged. We'll publish a new version of the plugin soon.

**Comment by pbihler** [comment]
Please merge PR #18 before publishing, it's an important fix for a nasty bug in PR #16 ...
