### ISSUE TITLE
Test results scroll bar missing

### ISSUE THREAD

**Issue by dwillsedulog** [TabDigital/atom-mocha-test-runner#48]
Using Atom version 1.2.1 and mocha-test-runner version 0.4.5. I noticed that after I updated to 1.2.1 the scroll bars for the results pane were missing. I can't scroll down to see the rest of the results.

![image](https://cloud.githubusercontent.com/assets/10818117/11243646/63a987e4-8dc6-11e5-82ce-b7680c953993.png)

**Comment by rprieto** [comment]
Thanks, this should be fixed by #47 that just landed. Can you try version `0.4.6` and let us know?

**Comment by dwillsedulog** [comment]
Looks like it's working now! Thanks!

**Comment by rprieto** [comment]
Good find. Happy to leave this issue (#48) open to discuss ideas/fixes.

**Comment by rprieto** [comment]
@dwillsedulog, a new fix from @myoushu was published as `0.4.7` which should fix everything! Cheers
