### ISSUE TITLE
Collapsed mode

### ISSUE THREAD

**Issue by rprieto** [TabDigital/atom-mocha-test-runner#5]
The plugin now has a `min-height` of 140px.
It could be great if:

- we could collapse it all the way down to the plugin's title bar
- it actually started collapsed
- clicking the title bar toggled between collapsed and expanded
- it remembered the last height (serialised)

**Comment by pbihler** [comment]
Implemented in PR #17

**Comment by rprieto** [comment]
#17 was merged, closing. Thanks again for the PR!
